# LiteLLM Configuration for Cost Optimization
# Place this in your project root as litellm_config.yaml

model_list:
  # Planning/Architecture - Expensive but smart
  - model_name: planning
    litellm_params:
      model: openrouter/anthropic/claude-3.5-sonnet
      api_key: os.environ/OPENROUTER_API_KEY
      
  # Implementation - Cheap and fast  
  - model_name: implementation
    litellm_params:
      model: openrouter/meta-llama/llama-3.1-8b-instruct
      api_key: os.environ/OPENROUTER_API_KEY
      
  # Review/Debug - Medium cost and capability
  - model_name: review
    litellm_params:
      model: openrouter/anthropic/claude-3-haiku
      api_key: os.environ/OPENROUTER_API_KEY

# Router settings for intelligent routing
router_settings:
  routing_strategy: "cost-optimization"
  fallback_models: ["planning"]
  retry_count: 2
  
# Cost tracking configuration
cost_tracking:
  enabled: true
  log_file: ".agent-os/cost-log.json"
  budget_alerts:
    daily_limit: 10.00
    warning_threshold: 0.80