litellm_settings:
  default_api_base: https://openrouter.ai/api/v1
  drop_params: True

model_list:
  - model_name: openrouter/qwen/qwen3-coder:free
    litellm_provider: openrouter
    api_key: os.environ/OPENROUTER_API_KEY

  - model_name: openrouter/google/gemini-pro
    litellm_provider: openrouter
    api_key: os.environ/OPENROUTER_API_KEY

  - model_name: openrouter/mistralai/mistral-7b-instruct
    litellm_provider: openrouter
    api_key: os.environ/OPENROUTER_API_KEY

  - model_name: openrouter/agentica-org/deepcoder-14b-preview
    litellm_provider: openrouter
    api_key: os.environ/OPENROUTER_API_KEY

  - model_name: openrouter/nousresearch/prometheus-2-7b-v2.0
    litellm_provider: openrouter
    api_key: os.environ/OPENROUTER_API_KEY