name: 📚 Documentation Issue
description: Report issues with documentation or suggest improvements
title: "[Docs]: "
labels: ["documentation", "triage"]
projects: ["k83-framework/1"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve K83 documentation! Clear docs help everyone use K83 more effectively.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing Documentation
        - Incorrect Information
        - Unclear Instructions
        - Broken Links
        - Typos/Grammar
        - Code Examples Don't Work
        - API Reference Issue
        - Tutorial Improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation issue? Provide URL, file path, or section name.
      placeholder: "https://github.com/your-repo/k83/blob/main/docs/... or docs/api/slash-commands.md"
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Content
      description: What does the documentation currently say? (Copy/paste relevant section)
      render: markdown
    validations:
      required: false

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe what's wrong or what's missing
      placeholder: "The documentation says... but it should say..."
    validations:
      required: true

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: How should this be fixed? Provide corrected text, new content, or suggestions.
      render: markdown
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional context that might help us understand the issue?
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/your-repo/k83/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true