# Ralex V2: OpenRouter-only LiteLLM Config (40 lines)
model_list:
  # Cheap model for simple tasks  
  - model_name: "cheap"
    litellm_params:
      model: "openrouter/google/gemini-flash-1.5"
      api_base: "https://openrouter.ai/api/v1"
      api_key: "${OPENROUTER_API_KEY}"
      max_tokens: 1000
      temperature: 0.3

  # Smart model for complex tasks
  - model_name: "smart"
    litellm_params:
      model: "openrouter/anthropic/claude-3.5-sonnet"
      api_base: "https://openrouter.ai/api/v1"
      api_key: "${OPENROUTER_API_KEY}"
      max_tokens: 4000
      temperature: 0.1

# Cost-conscious routing
router_settings:
  routing_strategy: "cost-based-routing"
  budget_manager:
    daily_limit: 5.00
    alert_threshold: 4.00
    currency: "USD"
  
  fallbacks:
    - ["cheap", "smart"]  # Always try cheap first

# Route by prompt patterns (yolo mode)
routing_rules:
  - pattern: "fix|typo|simple|quick|small|fast"
    model: "cheap"
    description: "Simple fixes and quick tasks"
  
  - pattern: "refactor|complex|analyze|review|architecture|design"
    model: "smart" 
    description: "Complex tasks requiring deeper reasoning"
    
  - pattern: "yolo|now|asap"
    model: "cheap"
    description: "Yolo mode - fast and cheap"
    
# Logging for cost tracking
litellm_settings:
  success_callback: ["budget_tracker"]
  set_verbose: true