# Free Mode Configuration

# Update frequency for free model tiers (in seconds)
# Default: 1 week (604800 seconds)
update_interval: 604800

# Model preferences for each tier (optional)
# These can be used to override the automatic selection if specific models are preferred.
# Example:
# base_tier_preferences:
#   - deepseek/deepseek-chat
#   - qwen/qwen-2.5-7b-instruct
# good_tier_preferences:
#   - anthropic/claude-3-haiku
#   - meta-llama/llama-3.1-70b-instruct
